// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGr5-9gnI12SGAozQUoP6pfFwcmiBaGMQ',
    appId: '1:1077822767651:web:fb191a5b0886ca6ced2796',
    messagingSenderId: '1077822767651',
    projectId: 'learningdart-8edef',
    authDomain: 'learningdart-8edef.firebaseapp.com',
    storageBucket: 'learningdart-8edef.appspot.com',
    measurementId: 'G-7HWTGFXLL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxspOYpWJ5sT9Pt2Kfro9eozK85c0O3xU',
    appId: '1:1077822767651:android:9526a636deda8e8aed2796',
    messagingSenderId: '1077822767651',
    projectId: 'learningdart-8edef',
    storageBucket: 'learningdart-8edef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYsvWeCK8TQ3jbzVi9oxGIQbvbKagR62M',
    appId: '1:1077822767651:ios:8b60c9175525f3d7ed2796',
    messagingSenderId: '1077822767651',
    projectId: 'learningdart-8edef',
    storageBucket: 'learningdart-8edef.appspot.com',
    iosClientId:
        '1077822767651-vrlb802nqvnhbpei1laghhv9p9hbg9ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYsvWeCK8TQ3jbzVi9oxGIQbvbKagR62M',
    appId: '1:1077822767651:ios:8b60c9175525f3d7ed2796',
    messagingSenderId: '1077822767651',
    projectId: 'learningdart-8edef',
    storageBucket: 'learningdart-8edef.appspot.com',
    iosClientId:
        '1077822767651-vrlb802nqvnhbpei1laghhv9p9hbg9ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
